# input data
base_dir: /content/drive/MyDrive/3dv-hw/3DV-2022
data_dir: ${base_dir}/data/chair
dtype: "mesh"
n_points: 2048
dim_voxels: 33

# loss weight
w_chamfer: 1.0
w_smooth: 0.1

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 10000

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 100
load_checkpoint: False

# eval
vis_freq: 1000
load_eval_checkpoint: True

